# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userID', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=32)),
                ('fullName', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=16)),
                ('orientation', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=64)),
                ('lastOnline', models.DateTimeField(verbose_name='last online')),
                ('interests', models.TextField()),
                ('interestTree', models.TextField()),
            ],
        ),
    ]
