# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 05:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='aboutMe',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
