# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 05:55
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20171014_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastOnline',
            field=models.DateTimeField(default=datetime.datetime(2017, 10, 14, 5, 55, 45, 926859, tzinfo=utc), verbose_name='last online'),
        ),
    ]
