# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-14 05:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_auto_20171014_0555'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='lastOnline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last online'),
        ),
    ]
